-- Import recipes from CSV
-- Note: Using gen_random_uuid() for new IDs, defaulting meal_type to 'brunch'

INSERT INTO recipes (id, name, english_name, type, suitable_for_vegetarian, suitable_for_vegan, description, meal_type)
VALUES
  (gen_random_uuid(), 'Huevos Revueltos', 'Scrambled Eggs', 'main', true, false, 'scrambled eggs', 'brunch'),
  (gen_random_uuid(), 'Tomate cubos', 'Cubed Tomatos', 'side', true, true, 'cubed tomatos with onions', 'brunch'),
  (gen_random_uuid(), 'Pico de Gallo', 'Pico Gallo Tomatos', 'side', true, true, 'cubed tomatos onions lemon and spices', 'brunch'),
  (gen_random_uuid(), 'Yogurt Natural Granola y Frutas', 'Granola Yogurt and Fruits', 'main', true, true, 'breakfast buffee', 'brunch'),
  (gen_random_uuid(), 'Guacamole', 'Guacamole', 'side', true, true, 'avocado mashed with spices', 'brunch'),
  (gen_random_uuid(), 'Gallo Pinto', 'Gallo Pinto', 'side', true, true, 'rice and beans costarrican style', 'brunch'),
  (gen_random_uuid(), 'Ensalada Normal', 'Salad', 'salad', true, true, 'normal salad with lettuce and veggies', 'dinner'),
  (gen_random_uuid(), 'Ensalada Mediterranea', 'Mediteranean Salad', 'salad', true, false, 'salad with cheese and olive oil', 'dinner'),
  (gen_random_uuid(), 'Ensalada Rallada', 'Root Salad', 'salad', true, true, 'salad with sliced beet and carrot', 'dinner'),
  (gen_random_uuid(), 'Vegetales al vapor', 'steamed vegetables', 'side', true, true, 'steamed veggies', 'dinner'),
  (gen_random_uuid(), 'Vegetales Salteados', 'cooked vegetables', 'side', true, true, 'veggies cooked in olive oil', 'dinner'),
  (gen_random_uuid(), 'Patacones', 'Fried Plantains', 'side', true, true, 'fried and compresed green plantain', 'dinner'),
  (gen_random_uuid(), 'Platano Maduro', 'Cooked Plantain', 'side', true, true, 'fried ripe plantain', 'dinner'),
  (gen_random_uuid(), 'Sopa de Vegetales', 'vegetable soup', 'soup', true, true, 'vegetable soup', 'dinner'),
  (gen_random_uuid(), 'Carne Olla de Carne', 'local beef soup', 'soup', false, false, 'meat for traditional olla de carne', 'dinner'),
  (gen_random_uuid(), 'Vegetales Olla de Carne', 'local soup', 'soup', true, true, 'veggies and roots for traditional olla de carne', 'dinner'),
  (gen_random_uuid(), 'Arroz Blanco', 'white rice', 'side', true, true, 'white rice side', 'dinner'),
  (gen_random_uuid(), 'Arroz Integral', 'brown rice', 'side', true, true, 'brown rice side', 'dinner'),
  (gen_random_uuid(), 'Cuz Cuz', 'Cuz Cuz', 'side', true, true, 'cuz cuz side', 'dinner'),
  (gen_random_uuid(), 'Pure de Camote', 'Mashed Sweet Potato', 'side', true, true, 'Mashed Potato side', 'dinner'),
  (gen_random_uuid(), 'Frijoles', 'beans', 'side', true, true, 'cooked red or black beans', 'dinner'),
  (gen_random_uuid(), 'Quinoa', 'Quinoa', 'side', true, true, 'quinoa with vegetables and spices', 'dinner'),
  (gen_random_uuid(), 'Arroz- Arroz con Pollo', 'Rice- rice with chicken', 'main', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Pollo- Arroz con Pollo', 'Chicken- rice with chicken', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Pollo en Salsa', 'chicken in sauce', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Pollo Plancha', 'grilled chicken', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Lomo Encebollado', 'steak with onions', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Carne en salsa', 'steak in sauce', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Pescado Plancha', 'grilled fish', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Tortillas de Maiz', 'corn tortillas', 'side', true, true, NULL, 'brunch'),
  (gen_random_uuid(), 'Tortillas de Lentejas', 'lentile tortilla', 'side', true, true, NULL, 'brunch'),
  (gen_random_uuid(), 'Ensalada de Papa', 'potato salad', 'salad', true, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Ensalada Rusa', 'Beet Salad', 'salad', true, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Picadillo de papa con zanahoria', 'potato and carrot picadillo', 'side', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Picadillo Carne Molida', 'ground beef picadillo', 'side', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Pure Yuca', 'yuca pure', 'side', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Yuca Frita', 'fried yuca', 'side', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Salsa Bolonesa', 'bolognese sauce', 'sauce', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Salsa Natural Pasta', 'pasta tomato sauce', 'sauce', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Pasta Arroz', 'rice pasta', 'main', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Pasta Fideos', 'pasta', 'main', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Rice and Beans', 'rice and beans', 'side', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Lentejas Sopa', 'lentile stew', 'main', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Pollo para lentejas Sopa', 'chicken for lentile stew', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Pollo Caribeno', 'caribean chicken', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Platano Caribeno', 'caribean plantain', 'main', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Pollo Mata Palo', 'Mata Palo Chicken', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Huevo Duro', 'boiled egg', 'side', true, false, NULL, 'brunch'),
  (gen_random_uuid(), 'Pad Thai', 'pad thai', 'main', true, true, NULL, 'dinner'),
  (gen_random_uuid(), 'Lasana Bolonesa', 'lasagna bolognese', 'main', false, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Lasana Vegana', 'vegan lasagna', 'main', true, false, NULL, 'dinner'),
  (gen_random_uuid(), 'Queso Frito', 'fried cheese', 'side', true, false, NULL, 'brunch')
ON CONFLICT DO NOTHING;
